---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: Auf der Dashboard-Seite befinden sich „Panels“, die die hohe Kapazität, Leistung und den Sicherheitszustand der von Ihnen überwachten Cluster anzeigen. Diese Seite enthält außerdem ein Fenster „Management Actions“, in dem Korrekturen aufgeführt sind, die Unified Manager zur Behebung bestimmter Ereignisse durchführen kann. 
---
= Dashboard-Seite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite Dashboard verfügt über „Bereiche“, in denen die allgemeine Kapazität, Performance und der Sicherheitszustand der von Ihnen überwachten Cluster angezeigt wird. Diese Seite enthält außerdem ein Fenster „Management Actions“, in dem Korrekturen aufgeführt sind, die Unified Manager zur Behebung bestimmter Ereignisse durchführen kann.

Die meisten Felder zeigen auch die Anzahl der aktiven Ereignisse in dieser Kategorie sowie die Anzahl der neuen Ereignisse an, die in den letzten 24 Stunden hinzugefügt wurden. Anhand dieser Informationen können Sie entscheiden, welche Cluster Sie möglicherweise weiter analysieren müssen, um Ereignisse zu lösen. Wenn Sie auf die Ereignisse klicken, werden die wichtigsten Ereignisse angezeigt und es wird ein Link zur Seite „Ereignismanagement“ angezeigt, die gefiltert wurde, um die aktiven Ereignisse in dieser Kategorie anzuzeigen.

Oben im Dashboard können Sie auswählen, ob in den Bedienfeldern Informationen für alle überwachten Cluster („Alle Cluster“) oder für einen einzelnen Cluster angezeigt werden. Sie können beispielsweise den Status aller Cluster anzeigen und anschließend bei Bedarf detaillierte Informationen zu einzelnen Clustern abrufen.

[NOTE]
====
Einige der unten aufgeführten Felder werden basierend auf Ihrer Konfiguration auf dem Dashboard angezeigt.

====


== Bereich „Verwaltungsaktionen“

Es gibt bestimmte Probleme, die Unified Manager sorgfältig analysieren und eine singuläre Lösung anbieten kann. Wenn verfügbar, werden diese Auflösungen in diesem Fenster mit der Schaltfläche *Fix IT* oder *Fix All* angezeigt. Diese Probleme können Sie sofort von Unified Manager beheben, anstatt ONTAP System Manager oder die ONTAP CLI zu verwenden. Um alle Probleme anzuzeigen, klicken Sie auf Siehe link:concept_fix_ontap_issues_directly_from_unified_manager.html["Behebung von ONTAP Problemen direkt über Unified Manager"] Finden Sie weitere Informationen.



== Kapazität Panel

Bei der Anzeige aller Cluster zeigt dieses Feld die physisch genutzte Kapazität (nach Anwendung der Speichereffizienzeinsparungen) und die physisch verfügbare Kapazität (ohne Berücksichtigung der potenziellen Speichereffizienzeinsparungen) für jeden Cluster an. Die Anzahl der Tage, bis die Festplatten voraussichtlich voll sind. Das Datenreduzierungsverhältnis (ohne Snapshot Kopien) basiert auf konfigurierten ONTAP Storage-Effizienzeinstellungen. Außerdem werden die genutzte Kapazität für alle konfigurierten Cloud-Tiers aufgelistet. Durch Klicken auf das Balkendiagramm gelangen Sie zur Seite „Aggregates Inventory“ für den Cluster. Wenn Sie auf den Text „Tage bis zum vollen“ klicken, wird eine Meldung angezeigt, die das Aggregat mit der geringsten Anzahl an verbleibenden Kapazitätstagen identifiziert. Klicken Sie auf den Aggregatnamen, um weitere Details zu erhalten.

Wenn Sie sich ein einzelnes Cluster anzeigen lassen, werden in diesem Bereich die genutzte physische Kapazität und physische verfügbare Kapazität für Datenaggregate angezeigt, die nach den einzelnen Festplattentypen auf der lokalen Tier und für die Cloud-Tier sortiert sind. Wenn Sie auf das Balkendiagramm für einen Festplattentyp klicken, gelangen Sie zur Seite Volume Inventory für die Volumes, die diesen Festplattentyp verwenden.



== Bereich Performance-Kapazität

Bei der Anzeige aller Cluster zeigt dieses Feld den Performance-Kapazitätswert für jedes Cluster (durchschnittlich über die vorherige 1 Stunde) und die Anzahl der Tage an, bis die Performance-Kapazität die Obergrenze erreicht (basierend auf der täglichen Wachstumsrate). Durch Klicken auf das Balkendiagramm gelangen Sie zur Seite „Nodes-Inventar“ für dieses Cluster. Auf der Seite Nodes-Inventar wird die Performancskapazität angezeigt, die über die letzten 72 Stunden Durchschnitt lag. Wenn Sie auf den Text „Tage bis zum vollen“ klicken, wird eine Meldung angezeigt, in der der Node mit der geringsten Anzahl an verbleibenden Performance-Kapazitätstagen identifiziert wird. Klicken Sie auf den Node-Namen, um weitere Details anzuzeigen.

Wenn Sie ein einzelnes Cluster anzeigen, werden in diesem Bereich die Werte der verwendeten Cluster-Performance-Kapazität, der IOPS-Gesamtwert und der Gesamtdurchsatz (MB/s) angezeigt. Die Anzahl der Tage, bis die drei Kennzahlen ihre Obergrenze erreichen sollen.



== Workload-IOPS-Bereich

Wenn Sie sich ein einzelnes Cluster anzeigen lassen, wird in diesem Bereich die Gesamtzahl der Workloads angezeigt, die derzeit in einem bestimmten IOPS-Bereich ausgeführt werden, und die Anzahl der einzelnen Festplattentypen wird angezeigt, wenn Sie den Mauszeiger über das Diagramm bewegen.



== Bereich „Workload Performance“

In diesem Fenster wird die Gesamtzahl der konformen und nicht konformen Workloads angezeigt, die jeder PSL-Richtlinie (Performance Service Level) zugewiesen sind. Außerdem wird die Anzahl der Workloads angezeigt, denen keine PSL zugewiesen ist. Durch Klicken auf ein Balkendiagramm gelangen Sie zu den Workloads, die dieser Richtlinie zugeordnet sind, auf der Seite Workloads. Wenn Sie auf das folgende Balkendiagramm klicken, gelangen Sie zu den Workloads, die dieser Richtlinie zugeordnet sind, die den entsprechenden Anforderungen nicht gerecht werden.



== Sicherheitstafel

Das Sicherheitsfenster zeigt je nach aktueller Ansicht den allgemeinen Sicherheitsstatus aller Cluster oder eines einzelnen Clusters an. In diesem Fenster wird Folgendes angezeigt:

* Eine Liste der Sicherheitsereignisse, die in den letzten 24 Stunden eingehen. Klicken Sie auf eine Veranstaltung, um die Details auf der Seite „Veranstaltungsdetails“ anzuzeigen
* Cluster-Sicherheitsstatus (Anzahl konformer und nicht konformer Cluster)
* Der Sicherheitsstatus der Storage-VM (Anzahl konformer und nicht konformer Storage VMs)
* Status der Volume-Verschlüsselung (Anzahl der verschlüsselten Volumes)
* Der Anti-Ransomware-Status des Volumes (Anzahl Volumes mit aktivierter oder deaktivierter Anti-Ransomware-Lösung)


Sie können auf die Balkendiagramme der Compliance-konformen und nicht konformen Cluster, Storage-VMS, verschlüsselten und nicht verschlüsselten Volumes und den Status für nicht-Ransomware-Volumes klicken, um zu den jeweiligen Seiten zu gelangen und die Sicherheitsinformationen für gefilterte Cluster, Storage-VMs und Volumes anzuzeigen.

Compliance basiert auf dem http://["NetApp Leitfaden zur verstärkte Sicherheit in ONTAP 9"]. Klicken Sie auf den Rechtspfeil oben im Bedienfeld, um die Sicherheitsinformationen für alle Cluster auf der Seite Sicherheit anzuzeigen. Weitere Informationen finden Sie unterlink:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Anzeigen des detaillierten Sicherheitsstatus für Cluster und Storage-VMs"].



== Data Protection Panel

In diesem Fenster wird die Zusammenfassung der Datensicherung für ein einzelnes oder alle Cluster in einem Rechenzentrum angezeigt. Sie zeigt die Gesamtzahl der Datensicherungsereignisse, MetroCluster-Ereignisse und die Anzahl der aktiven Ereignisse an, die in den letzten 24 Stunden in ONTAP angesprochen wurden. Wenn Sie auf den Link der einzelnen Veranstaltungen klicken, gelangen Sie zur Seite Veranstaltungsdetails. Sie können auf den Link * Alle anzeigen* klicken, um alle aktiven Schutzereignisse auf der Seite Ereignisverwaltung Inventar anzuzeigen. Das Fenster zeigt:

* Die Anzahl der Volumes in einem Cluster oder alle Cluster in einem durch Snapshot Kopien geschützten Datacenter.
* Die Anzahl der Volumes in einem Cluster oder alle Cluster in einem durch SnapMirror Beziehungen geschützten Datacenter. Für SnapMirror Beziehungen wird die Anzahl der Volumes im Quell-Cluster berücksichtigt.
* Die Anzahl der Cluster oder alle Cluster in einem durch MetroCluster-Konfiguration geschützten Datacenter über IP oder FC
* Die Anzahl der Volume-Beziehungen mit der SnapMirror Recovery Point Objective (RPO)-Verzögerung basierend auf dem lag-Status.


Sie können mit der Maus die entsprechenden Zählungen und Legenden anzeigen. Sie können auf den Rechtspfeil oben im Bedienfeld klicken, um die Details für einen einzelnen oder alle Cluster auf der Datenschutzseite anzuzeigen. Sie können außerdem auf klicken:

* Die Balkendiagramme für nicht geschützte Volumes und durch Snapshot-Kopien geschützte Volumes sind, werden zur Seite „Volumes“ und zur Ansicht der Details angezeigt.
* Die Balkendiagramme für die durch MetroCluster-Konfiguration geschützten oder nicht geschützten Cluster werden angezeigt, um zur Seite Cluster zu gelangen und die Details anzuzeigen.
* Die Balkendiagramme für alle Beziehungen gehen zur Seite „Beziehungen“, auf der die Details nach dem Quellcluster gefiltert werden.


Weitere Informationen finden Sie unter link:../data-protection/view-protection-status.html["Anzeigen des Volume-Sicherungsstatus"].



== Das Fenster „Verwendungsübersicht“

Bei der Anzeige aller Cluster können Sie Cluster nach den höchsten IOPS, dem höchsten Durchsatz (MB/s) oder der am höchsten genutzten physischen Kapazität anzeigen.

Bei der Anzeige eines einzelnen Clusters können Sie Workloads nach den höchsten IOPS, dem höchsten Durchsatz (MB/s) oder der am höchsten genutzten logischen Kapazität anzeigen.

*Verwandte Informationen*

link:../events/task_fix_issues_using_um_automatic_remediations.html["Behebung von Problemen durch automatische Problembehebung mit Unified Manager"]

link:../performance-checker/task_display_information_about_performance_event.html["Anzeigen von Informationen zu Performance-Ereignissen"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["Performance-Management mithilfe von Performance-Kapazität und verfügbaren IOPS-Informationen"]

link:../health-checker/reference_health_volume_details_page.html["Seite „Volume/Health Details“"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["Performance-Ereignisanalyse und -Benachrichtigung"]

link:../events/reference_description_of_event_severity_types.html["Beschreibung der Ereignistypen"]

link:../performance-checker/concept_sources_of_performance_events.html["Quellen von Leistungsereignissen"]

link:../health-checker/concept_manage_cluster_security_objectives.html["Verwalten von Zielen für die Cluster-Sicherheit"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["Monitoring der Cluster-Performance über die Startseite des Performance Cluster"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["Überwachung der Performance mithilfe der Seiten „Performance Inventory“ (Performance-Bestandsaufnahme"]
