---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: Sie können den allgemeinen Zustand der logischen Verbindungen überwachen und diagnostizieren, während Sie gleichzeitig die Daten spiegeln. Sie können die Probleme oder Risiken identifizieren, die die Spiegelung von Cluster-Komponenten wie Aggregaten, Nodes und Storage Virtual Machines unterbrechen. 
---
= Monitoring der MetroCluster Replizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den allgemeinen Zustand der logischen Verbindungen überwachen und diagnostizieren, während Sie gleichzeitig die Daten spiegeln. Sie können die Probleme oder Risiken identifizieren, die die Spiegelung von Cluster-Komponenten wie Aggregaten, Nodes und Storage Virtual Machines unterbrechen.

Unified Manager überwacht mit Systemzustandsmeldungen den Status der Komponenten und die Konnektivität in der MetroCluster-Konfiguration.

*Was Sie brauchen*

Der lokale und der Remote-Cluster in der MetroCluster Konfiguration müssen Unified Manager hinzugefügt werden



== Anzeigen der Replikation für MetroCluster-über-IP-Konfigurationen

Bei MetroCluster-over-IP-Konfigurationen wird der Datenreplizierungsstatus in der Topologieansicht für einen durch MetroCluster over IP geschützten Cluster aus den folgenden Ansichten im linken Navigationsbereich von Unified Manager angezeigt:

* *Speicherung* > *Cluster* > *Schutz: Ansicht MetroCluster*
* *Schutz* > *Beziehungen* > *Beziehung: MetroCluster* Ansicht


Weitere Informationen finden Sie unter link:../storage-mgmt/task_monitor_metrocluster_configurations.html#monitor-connectivity-issues-in-metrocluster-over-ip["Überwachen Sie Konnektivitätsprobleme in MetroCluster über IP"].



== Anzeigen der Replizierung für MetroCluster über FC-Konfigurationen

Befolgen Sie diese Schritte, um alle Probleme in der Datenreplizierung für die MetroCluster-over-FC-Konfiguration zu ermitteln.

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Storage* > *Cluster*.
+
Eine Liste der überwachten Cluster wird angezeigt.

. Klicken Sie in der Ansicht *Systemzustand: Alle Cluster* auf den Namen des Clusters, für den Sie MetroCluster-Replikationsdetails anzeigen möchten. Klicken Sie auf der Seite *Cluster / Health Details* auf die Registerkarte *MetroCluster-Replikation*.
+
Die Topologie der zu replizierenden MetroCluster Konfiguration wird am lokalen Standort im entsprechenden Cluster-Objektbereich mit den Informationen zum Remote-Standort angezeigt, an dem die Daten gespiegelt werden. Wenn Sie den Mauszeiger über das Symbol bewegen, können Sie detaillierte Informationen zum generierten Ereignis anzeigen.



Sie können die auf der Seite Cluster/Health Details angezeigten Informationen verwenden, um alle Replikationsprobleme zu beheben. Wenn Sie Spiegelungsprobleme in Ihrer MetroCluster Konfiguration feststellen, müssen Sie sich bei System Manager einloggen oder auf die ONTAP CLI zugreifen, um die Probleme zu beheben.

*Verwandte Informationen*

link:../health-checker/reference_health_cluster_details_page.html["„Cluster/Systemzustand“-Details"]
