---
permalink: storage-mgmt/task_view_list_of_monitored_clusters.html 
sidebar: sidebar 
keywords: view, list, monitored, clusters 
summary: Mithilfe der Seite Cluster Setup können Sie das Inventar der Cluster anzeigen. Sie können Details zu den Clustern anzeigen, z. B. ihren Namen oder ihre IP-Adresse und ihren Kommunikationsstatus. 
---
= Anzeigen der Liste der überwachten Cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Seite Cluster Setup können Sie das Inventar der Cluster anzeigen. Sie können Details zu den Clustern anzeigen, z. B. ihren Namen oder ihre IP-Adresse und ihren Kommunikationsstatus.

*Was Sie brauchen*

Sie müssen über die Rolle „Operator“, „Application Administrator“ oder „Storage Administrator“ verfügen.

.Schritt
. Klicken Sie im linken Navigationsbereich auf *Storage-Management* > *Cluster-Setup*.
+
Es werden alle Cluster in der Storage-Umgebung angezeigt, die von Unified Manager gemanagt werden. Die Liste der Cluster ist nach der Spalte mit dem Schweregrad des Erfassungsstatus sortiert. Sie können auf eine Spaltenüberschrift klicken, um die Cluster nach unterschiedlichen Spalten zu sortieren.


