---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: Kurzanleitung für Unified Manager auf VMware vSphere Plattform. 
---
= Schnellstartanleitung für VMware Installationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die herunterladen `.tar` Datei, die ein Stammzertifikat enthält, a `README` Datei und an `OVA` Datei und stellen Sie Unified Manager als virtuelle Appliance bereit.



== Systemanforderungen

* Betriebssystem: VMware ESXi 8.0
* RAM: 12 GB
* CPU: Insgesamt 9572 MHz
* Freier Speicherplatz: 5 GB (Thin Provisioning), 152 GB (Thick Provisioning)


Detaillierte Systemanforderungen finden Sie im link:../install-vapp/concept_requirements_for_installing_unified_manager.html["Anforderungen für die Installation von Unified Manager"] Und link:http://mysupport.netapp.com/matrix["Interoperabilitätsmatrix"].



== Installation von Active IQ Unified Manager



=== Laden Sie das Installationsprogramm herunter

. Laden Sie die herunter `.tar` Datei, die ein Stammzertifikat enthält, a `README` Datei und an `OVA` Datei:
. Speichern Sie die Datei in einem lokalen Verzeichnis oder Netzwerkverzeichnis, auf das Ihr vSphere Client zugreifen kann.
. In dem Verzeichnis, in dem Sie das heruntergeladen haben `.tar` Datei, geben Sie das ein `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz` Befehl. + das erforderliche `OVA` Datei, ein Stammzertifikat und ein `README` Die Datei wird in das Zielverzeichnis entpackt.




=== Überprüfen Sie die Integrität

Sie können die Integrität des überprüfen `OVA` Führen Sie die Schritte aus, die im aufgeführt sind `README` Datei:



=== Installation Von Unified Manager

. Klicken Sie im vSphere-Client auf *Datei > OVF-Vorlage bereitstellen*.
. Suchen Sie die OVA-Datei und stellen Sie die virtuelle Appliance mithilfe des Assistenten auf dem ESXi-Server bereit.
. Auf der Seite „Prüfungsdetails“ im Abschnitt „Herausgeber“ wird die Meldung angezeigt  `Entrust Code Signing - OVCS2 (Trusted certificate)` Bestätigt die Integrität des Downloads `OVA` Datei: Für die Nachricht `Entrust Code Signing - OVCS2 (Invalid certificate)`, Aktualisieren Sie den VMware vCenter Server auf 7.0U3E oder eine höhere Version.
. Füllen Sie auf der Seite Vorlage anpassen auf der Registerkarte Eigenschaften die Felder aus, die für den Installationstyp erforderlich sind:
+
** Geben Sie für die statische Konfiguration die erforderlichen Informationen in alle Felder ein. Das Hinzufügen von Informationen für das Feld *Secondary DNS* ist nicht erforderlich.
** Wenn DHCP unter IPv4 verwendet wird, fügen Sie in keinem Feld Informationen hinzu.
** Aktivieren Sie für DHCP unter Verwendung von IPv6 das Kontrollkästchen „Automatische IPv6-Adresse aktivieren“. Fügen Sie in keinem anderen Feld Informationen hinzu.


. Schalten Sie die VM ein.
. Klicken Sie auf die Registerkarte Konsole, um den anfänglichen Startvorgang anzuzeigen.
. Zeitzone konfigurieren.
. Geben Sie einen Benutzernamen und ein Passwort für die Unified Manager-Wartung ein.


Am Ende der Installation werden die Informationen zur Verbindung mit der Unified Manager Web-Benutzeroberfläche angezeigt.
