---
permalink: install-windows/task_uninstall_unified_manager_win.html 
sidebar: sidebar 
keywords: uninstall, unified manager 
summary: Sie können Unified Manager deinstallieren, indem Sie den Assistenten Programme und Funktionen verwenden oder eine unbeaufsichtigte Deinstallation von der Befehlszeilenschnittstelle durchführen. 
---
= Deinstallieren Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Sie können Unified Manager deinstallieren, indem Sie den Assistenten Programme und Funktionen verwenden oder eine unbeaufsichtigte Deinstallation von der Befehlszeilenschnittstelle durchführen.

*Was Sie brauchen*

* Sie müssen über Administratorrechte für Windows verfügen.
* Alle Cluster (Datenquellen) müssen vom Unified Manager-Server entfernt werden, bevor die Software deinstalliert wird.
* Sie sollten die Firewall-Regeln, die erstellt werden, manuell löschen, um MySQL-Port 3306 zu ermöglichen oder zu blockieren. Die Firewall-Regeln werden nicht automatisch gelöscht.


.Schritte
. Deinstallieren Sie Unified Manager, indem Sie eine der folgenden Optionen auswählen:
+
** Wenn Sie Unified Manager aus dem Assistenten für Programme und Funktionen* deinstallieren, führen Sie die folgenden Schritte aus:
+
... Navigieren Sie zu *Systemsteuerung* > *Programm und Funktionen*.
... Wählen Sie Active IQ Unified Manager, und klicken Sie auf *Deinstallieren*.


** Wenn Sie Unified Manager von der Befehlszeile deinstallieren, führen Sie die folgenden Schritte aus:
+
... Melden Sie sich mit Administratorrechten an der Windows-Befehlszeile an.
... Navigieren Sie zum Active IQ Unified Manager-Verzeichnis, und führen Sie den folgenden Befehl aus:
+
`+msiexec /x {A78760DB-7EC0-4305-97DB-E4A89CDFF4E1} /qn /l*v %systemdrive%\UmUnInstall.log+`

+
Wenn die Benutzerkontensteuerung (UAC) auf dem Server aktiviert ist und Sie als Domänenbenutzer angemeldet sind, müssen Sie die Methode zur Deinstallation der Befehlszeile verwenden.

+
Unified Manager wird von Ihrem System deinstalliert.





. Deinstallieren Sie die folgenden Pakete und Daten von Drittanbietern, die während der Deinstallation von Unified Manager nicht entfernt werden:
+
** Pakete von Drittanbietern: JRE, MySQL, Microsoft Visual C&#43;&#43; 2015 Redistributable, Python, Und 7zip
** MySQL Applikationsdaten von Unified Manager
** Anwendungsprotokolle und Inhalt des Applikationsdatenverzeichnisses



