---
section: config
title: Durchführung von Konfigurations- und Administrationsaufgaben
entries:
- title: Konfigurieren Sie Active IQ Unified Manager
  url: "/config/concept_configure_unified_manager.html"
  entries:
  - title: Überblick über die Konfigurationssequenz
    url: "/config/concept_overview_of_configuration_sequence.html"
  - title: Zugriff auf die Unified Manager-Web-Benutzeroberfläche
    url: "/config/task_access_unified_manager_web_ui.html"
  - title: Führen Sie die Ersteinrichtung der Unified Manager-Web-Benutzeroberfläche
      durch
    url: "/config/task_perform_initial_setup_of_unified_manager_web_ui.html"
  - title: Fügen Sie Cluster hinzu
    url: "/config/task_add_clusters.html"
  - title: Konfigurieren Sie Unified Manager zum Senden von Warnbenachrichtigungen
    url: "/config/task_configure_unified_manager_to_send_alert_notifications.html"
    entries:
    - title: Konfigurieren Sie die Einstellungen für Ereignisbenachrichtigungen
      url: "/config/task_configure_event_notification_settings.html"
    - title: Aktivieren Sie die Remote-Authentifizierung
      url: "/config/task_enable_remote_authentication.html"
    - title: Deaktivieren der Remote-Authentifizierung für verschachtelte Gruppen
      url: "/config/task_disable_nested_groups_from_remote_authentication.html"
    - title: Einrichten von Authentifizierungsdiensten
      url: "/config/task_set_up_authentication_services.html"
    - title: Authentifizierungsserver hinzufügen
      url: "/config/task_add_authentication_servers.html"
    - title: Testen Sie die Konfiguration der Authentifizierungsserver
      url: "/config/task_test_configuration_of_authentication_servers_um_6_0.html"
    - title: Warnmeldungen hinzufügen
      url: "/config/task_add_alerts.html"
  - title: Ändern des lokalen Benutzerkennworts
    url: "/config/task_change_local_user_password.html"
  - title: Legen Sie das Zeitlimit für die Inaktivität der Sitzung fest
    url: "/config/task_set_session_inactivity_timeout.html"
  - title: Legen Sie das Sitzungs-Timeout über CLI fest
    url: "/config/task_set_session_timeout_CLI.html"
  - title: Ändern des Unified Manager-Hostnamens
    url: "/config/concept_change_unified_manager_host_name.html"
    entries:
    - title: Ändern des Hostnamens der virtuellen Unified Manager-Appliance
      url: "/config/task_change_unified_manager_host_name_on_vmware.html"
      entries:
      - title: Generieren eines HTTPS-Sicherheitszertifikats
        url: "/config/task_generate_an_https_security_certificate_ocf.html"
      - title: Starten Sie die Virtual Machine von Unified Manager neu
        url: "/config/task_restart_unified_manager_virtual_machine.html"
    - title: Ändern des Unified Manager-Hostnamens auf Linux-Systemen
      url: "/config/task_change_um_host_name_on_rhel.html"
  - title: Aktivieren und Deaktivieren der richtlinienbasierten Speicherverwaltung
    url: "/config/task_enable_and_disable_policy_based_storage_management.html"
- title: Konfigurieren der Unified Manager-Sicherung
  url: "/config/concept_configure_um_backup.html"
- title: Funktionseinstellungen verwalten
  url: "/config/concept_manage_feature_settings.html"
  entries:
  - title: Richtlinienbasiertes Storage-Management
    url: "/config/concept_policy_based_storage_management.html"
  - title: API-Gateway aktivieren
    url: "/config/concept_api_gateway.html"
  - title: Inaktivitäts-Timeout angeben
    url: "/config/concept_inactivity_timeout.html"
  - title: Aktivieren von Active IQ-Portalereignissen
    url: "/config/concept_active_iq_platform_events.html"
  - title: Aktivieren und Deaktivieren von Sicherheitseinstellungen zur Einhaltung
      der Vorschriften
    url: "/config/concept_security_dashboard.html"
  - title: Aktivieren und Deaktivieren des Skript-Uploads
    url: "/config/task_enable_and_disable_ability_to_upload_scripts.html"
  - title: Fügen Sie ein Anmeldebanner hinzu
    url: "/config/concept_login_banner.html"
- title: Verwenden der Wartungskonsole
  url: "/config/task_use_maintenance_console.html"
  entries:
  - title: Welche Funktionen bietet die Wartungskonsole
    url: "/config/concept_what_functionality_maintenance_console_provides.html"
  - title: Was der Wartungsbenutzer tut
    url: "/config/concept_what_maintenance_user_does.html"
  - title: Funktionen von Benutzern zur Diagnose
    url: "/config/concept_what_diagnostic_user_does.html"
  - title: Öffnen Sie die Wartungskonsole
    url: "/config/task_access_maintenance_console.html"
  - title: Zugriff auf die Wartungskonsole über die vSphere-VM-Konsole
    url: "/config/task_access_maintenance_console_using_vsphere.html"
  - title: Menüs für Wartungskonsolen
    url: "/config/concept_maintenance_console_menu.html"
    entries:
    - title: Menü Netzwerkkonfiguration
      url: "/config/reference_network_configuration_menu.html"
    - title: Menü Systemkonfiguration
      url: "/config/reference_system_configuration_menu.html"
    - title: Menü „Support und Diagnose“
      url: "/config/reference_support_and_diagnostics_menu.html"
    - title: Zusätzliche Menüoptionen
      url: "/config/reference_additional_menu_options.html"
  - title: Ändern des Wartungsbenutzerkennworts unter Windows
    url: "/config/task_change_maintenance_user_password_on_windows.html"
  - title: Ändern des Umadmin-Passworts auf Linux-Systemen
    url: "/config/task_change_umadmin_password_on_rhel.html"
  - title: Ändern Sie die Ports, die Unified Manager für HTTP- und HTTPS-Protokolle
      verwendet
    url: "/config/task_change_ports_um_uses_for_http_and_https_protocols.html"
  - title: Netzwerkschnittstellen hinzufügen
    url: "/config/task_add_additional_network_interfaces.html"
  - title: Fügen Sie dem Unified Manager-Datenbankverzeichnis Speicherplatz hinzu
    url: "/config/concept_add_disk_space_to_um_database_directory.html"
    entries:
    - title: Fügen Sie dem Datenverzeichnis des Linux-Hosts Speicherplatz hinzu
      url: "/config/task_add_space_to_data_directory_of_um_linux_host.html"
    - title: Fügen Sie Speicherplatz zur Datenfestplatte der virtuellen VMware-Maschine
        hinzu
      url: "/config/task_add_space_to_data_disk_of_vmware_virtual_machine.html"
    - title: Fügen Sie dem logischen Laufwerk des Microsoft Windows-Servers Speicherplatz
        hinzu
      url: "/config/task_add_space_to_data_disk_of_windows_server.html"
- title: Managen Sie den Benutzerzugriff
  url: "/config/concept_manage_user_access.html"
  entries:
  - title: Benutzer hinzufügen
    url: "/config/task_add_users.html"
    entries:
    - title: Erstellen eines Datenbankbenutzers
      url: "/config/task_create_database_user.html"
  - title: Bearbeiten der Benutzereinstellungen
    url: "/config/task_edit_user_setts.html"
  - title: Benutzer anzeigen
    url: "/config/task_view_users.html"
  - title: Löschen von Benutzern oder Gruppen
    url: "/config/task_delete_users_or_groups.html"
  - title: Was RBAC ist
    url: "/config/concept_what_rbac_is.html"
  - title: Was ist die rollenbasierte Zugriffssteuerung
    url: "/config/concept_what_role_based_access_control_does.html"
  - title: Definitionen der Benutzertypen
    url: "/config/reference_definitions_of_user_types.html"
  - title: Definitionen von Benutzerrollen
    url: "/config/reference_definitions_of_user_roles.html"
  - title: Unified Manager Benutzer-Rollen und -Funktionen
    url: "/config/reference_unified_manager_roles_and_capabilities.html"
- title: Verwalten der SAML-Authentifizierungseinstellungen
  url: "/config/concept_manage_saml_authentication_settings_um.html"
  entries:
  - title: Anforderungen an Identitätsanbieter
    url: "/config/reference_identity_provider_requirements_um.html"
  - title: Aktivieren Sie die SAML-Authentifizierung
    url: "/config/task_enable_saml_authentication_um.html"
  - title: Ändern des für die SAML-Authentifizierung verwendeten Identitätsanbieters
    url: "/config/task_change_identity_provider_idp_used_for_saml_authentication.html"
  - title: Aktualisieren Sie die SAML-Authentifizierungseinstellungen nach der Änderung
      des Unified Manager-Sicherheitszertifikats
    url: "/config/task_update_saml_authentication_after_um_certificate_change.html"
  - title: Deaktivieren Sie die SAML-Authentifizierung
    url: "/config/task_disable_saml_authentication_um.html"
  - title: Deaktivieren der SAML-Authentifizierung über die Wartungskonsole
    url: "/config/task_disable_saml_authentication_from_maintenance_console_um.html"
  - title: Seite SAML Authentication
    url: "/config/reference_saml_authentication_page_um.html"
- title: Verwalten der Authentifizierung
  url: "/config/concept_manage_authentication.html"
  entries:
  - title: Authentifizierungsserver bearbeiten
    url: "/config/task_edit_authentication_servers.html"
  - title: Authentifizierungsserver löschen
    url: "/config/task_delete_authentication_servers.html"
  - title: Authentifizierung mit Active Directory oder OpenLDAP
    url: "/config/concept_authentication_with_active_directory_or_openldap.html"
  - title: Audit-Protokollierung
    url: "/config/concept_audit_logging.html"
    entries:
    - title: Konfigurieren von Überwachungsprotokollen
      url: "/config/task_configure_audit_logs.html"
    - title: Aktivieren der Remote-Protokollierung von Überwachungsprotokollen
      url: "/config/task_enable_remote_logging_of_audit_logs.html"
  - title: Seite „Remote Authentication“
    url: "/config/reference_remote_authentication_page.html"
- title: Verwalten von Sicherheitszertifikaten
  url: "/config/concept_manage_security_certificates_ocf.html"
  entries:
  - title: Zeigen Sie das HTTPS-Sicherheitszertifikat an
    url: "/config/task_view_https_security_certificate_ocf.html"
  - title: Laden Sie eine HTTPS-Zertifikatsignieranforderung herunter
    url: "/config/task_download_an_https_certificate_sign_request_ocf.html"
  - title: Installieren Sie ein von einer Zertifizierungsstelle signiertes und zurückgegebenes
      HTTPS-Zertifikat
    url: "/config/task_install_ca_signed_and_returned_https_certificate.html"
  - title: Installieren Sie ein mit externen Tools generiertes HTTPS-Zertifikat
    url: "/config/concept_install_https_certificate_generated_using_external_tools.html"
  - title: Seitenbeschreibungen zur Zertifikatverwaltung
    url: "/config/concept_page_descriptions_for_certificate_management.html"
    entries:
    - title: Seite „HTTPS-Zertifikat“
      url: "/config/reference_https_dialog_box_ocf.html"
    - title: Dialogfeld „HTTPS-Zertifikat neu erstellen“
      url: "/config/reference_regenerate_https_certificate_dialog_box.html"
