---
permalink: config/task_regenerate_client_certificate.html 
sidebar: sidebar 
keywords: client certificate, regenerate, validity, maintenance console 
summary: Sie können die Wartungskonsole verwenden, um Ihr Unified Manager-Client-Zertifikat neu zu generieren. 
---
= Regenerieren Sie das Unified Manager-Clientzertifikat.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Wartungskonsole verwenden, um Ihr Unified Manager-Client-Zertifikat neu zu generieren.  Ihr Zertifikat hat eine verlängerte Gültigkeitsdauer von fünf Jahren.

.Schritte
. Melden Sie sich als Wartungsbenutzer an.
. Wählen Sie *Client-Zertifikat neu generieren* und drücken Sie die *Eingabetaste*.
. Wenn das System zur Authentifizierung auffordert, geben Sie die erforderlichen Anmeldeinformationen ein.
. Wählen Sie *Regeneration bestätigen* und drücken Sie *Eingabe*.
. Nachdem das Zertifikat neu generiert wurde, starten Sie den Unified Manager-Dienst neu, um die Änderungen anzuwenden.
. Um das aktualisierte Zertifikat zu überprüfen, melden Sie sich bei ONTAP an.  Zeigen Sie den Status und den Gültigkeitsstatus des Client-Zertifikats an.


*Verwandte Informationen*  https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Verwalten Sie ONTAP -Zertifikate mit System Manager"^]
