---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Kurzanleitung für Unified Manager auf der Linux-Plattform. 
---
= Kurzanleitung für Linux-Installationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Installationspaket herunterladen und Unified Manager auf einer physischen oder virtuellen Red hat Enterprise Linux-Plattform installieren.



== Systemanforderungen

* Betriebssystem: Red hat Enterprise Linux Versionen 8.x und 9.4, basierend auf x86_64 Architektur, installiert unter Verwendung der „Server mit GUI“ Basisumgebung aus der Option *Software Selection* des OS Installers
* RAM: 12 GB, CPU: 9572 MHz insgesamt
* Freier Speicherplatz: 100 GB Festplattenspeicher im `/opt/netapp/data` Verzeichnis, 50 GB in der Root-Partition. Für die separate Montage `/opt` Und `/var/log` Verzeichnisse, stellen Sie sicher, dass `/opt` Hat 15 GB, `/var/log` Hat 16 GB, und `/tmp` Verfügt über 10 GB freien Speicherplatz.


Detaillierte Systemanforderungen und Informationen zur Installation des Produkts an einem gesicherten Standort finden Sie im link:../install-linux/concept_requirements_for_install_unified_manager.html["Anforderungen für die Installation von Unified Manager"] Und das link:http://mysupport.netapp.com/matrix["Interoperabilitätsmatrix"].



== Installation von Active IQ Unified Manager



=== Laden Sie das Installationsprogramm herunter

. Laden Sie die herunter `ActiveIQUnifiedManager-<version>.zip` Installationspaket und Code-Signing-Zertifikat (`.pem`) Und digitale Signatur (`.sig`) .
. Führen Sie im Verzeichnis, in dem Sie die Installationsdatei heruntergeladen haben, folgende Schritte aus:
+
`# unzip ActiveIQUnifiedManager-<version>.zip`





=== Überprüfen Sie die Integrität

Führen Sie die folgenden Befehle aus, um die Integrität des Installationspakets zu überprüfen:

* Laufen `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>` Erstellen einer Datei mit dem öffentlichen Schlüssel aus dem Code-Signierungszertifikat.
* Laufen `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip` So überprüfen Sie die Signatur des Installationspakets.




=== Überprüfung der Repository-Konfiguration

Die Verfahren zur Konfiguration eines Red hat Enterprise Linux-Repository sind standortspezifisch. Sie können das im Installationspaket enthaltene Skript verwenden `pre_install_check.sh`, um die Konfiguration Ihres Betriebssystems zu überprüfen. Wenn Ihr System mit dem Internet verbunden ist, erhalten Sie automatisch Anweisungen zur Einrichtung des Red hat Enterprise Linux Repository.

`# sudo ./pre_install_check.sh`



=== Installation Von Unified Manager

Unified Manager verwendet das `yum` Dienstprogramm zur Installation der Software und jeglicher abhängiger Software. Da es unterschiedliche Images von Red hat Enterprise Linux gibt, hängen die installierten Pakete von der in den Images vorhandenen Software ab. Das `yum` Dienstprogramm bestimmt die abhängigen Softwarepakete für die Installation. Weitere Informationen zu den abhängigen Softwarepaketen finden Sie im link:../install-linux/reference_red_hat_software_and_installation_requirements.html["Linux-Software- und Installationsanforderungen"].

Um Unified Manager zu installieren, führen Sie den folgenden Befehl aus, entweder als Root-Benutzer oder mit `sudo`, Aus dem Verzeichnis, in dem die Installationsdatei entpackt wurde:

`# yum install netapp-um<version>.x86_64.rpm`

Oder

`% sudo yum install netapp-um<version>.x86_64.rpm`

Am Ende der Installation werden die Informationen zur Verbindung mit der Unified Manager Web-Benutzeroberfläche angezeigt. Wenn Sie keine Verbindung zur Web-Benutzeroberfläche herstellen können, lesen Sie den `README` Datei mit der Software für weitere Informationen über Port 443 Einschränkungen verpackt.
