---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: Das Linux-System, auf dem Unified Manager installiert wird, erfordert bestimmte Versionen des Betriebssystems und unterstützende Software. 
---
= Linux-Software- und Installationsanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Linux-System, auf dem Unified Manager installiert wird, erfordert bestimmte Versionen des Betriebssystems und unterstützende Software.



== Betriebssystem-Software

Das Linux-System muss die folgenden Versionen des Betriebssystems und die unterstützende Software installiert haben:

* Red hat Enterprise Linux Versionen 8.x und 9.4, basierend auf x86_64-Architektur.


In der Interoperabilitäts-Matrix finden Sie die vollständige und aktuelle Liste der unterstützten Red hat Enterprise Linux-Versionen.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

Der Server sollte dediziert sein für die Ausführung von Unified Manager. Auf dem Server sollten keine anderen Anwendungen installiert sein. Es ist möglich, dass Vulnerability Scanner wie Qualys auf Ihrem Linux-System aufgrund von Unternehmensvorschriften installiert ist. Sie sollten den Schwachstellenscanner vor der Installation von Unified Manager deaktivieren, um einen Fehler bei der Installation zu verhindern.


NOTE: Schwachstellenscanner (wie Qualys) können zu einer hohen CPU-Auslastung führen, wenn die virtuelle Maschine (VM) intern (wo Unified Manager und der Schwachstellenscanner auf derselben VM installiert sind) oder extern gescannt wird (wobei Unified Manager und der Schwachstellenscanner auf zwei verschiedenen Servern installiert sind und der Schwachstellenscanner die VM scannt, auf der Unified Manager installiert ist). Dieses Problem führt häufig dazu, dass die VM nicht reagiert und die Unified Manager-Services beeinträchtigt werden. Daher empfiehlt NetApp, die Schwachstellenprüfung in der VM zu deaktivieren, auf der Unified Manager installiert ist. Wenn keine Option zum Deaktivieren des Scanners besteht, scannen Sie die VM außerhalb der Geschäftszeiten und starten Sie die Services nach Abschluss des Scanvorgangs neu.



== Software von anderen Anbietern

Unified Manager wird auf einem WildFly Web-Server bereitgestellt. WildFly 26.1.3 ist gebündelt und mit Unified Manager konfiguriert.

Die folgenden Drittanbieterpakete sind erforderlich, jedoch nicht in Unified Manager enthalten. Diese Pakete werden automatisch vom installiert `yum` Installationsprogramm während der Installation, vorausgesetzt, Sie haben die Repositories wie in den folgenden Abschnitten beschrieben konfiguriert.

* MySQL Community Edition Version 8.4.4 (aus dem MySQL-Repository)
* OpenJDK Version 11.0.25 (aus dem Red hat Extra Enterprise Linux Server-Repository)
* Python 3.9.x (aus dem Repository von Red hat Extra Enterprise Linux Server)
* P7zip Version 16.02 oder höher (aus dem Red hat Extra Packages for Enterprise Linux Repository)


[NOTE]
====
Vor dem Upgrade von Software anderer Anbieter müssen Sie eine laufende Instanz von Unified Manager herunterfahren. Nach Abschluss der Softwareinstallation von Drittanbietern können Sie Unified Manager neu starten.

====


== Anforderungen an die Benutzerautorisierung

Die Installation von Unified Manager auf einem Linux-System kann vom Root-Benutzer oder von nicht-Root-Benutzern mit dem durchgeführt werden `sudo` Befehl.

Zusätzlich umfasst die Standard-Unified Manager-Installation den umadmin-Benutzer (Standard-Wartungsbenutzer) und den jboss-Benutzer in den sudoers-Dateien (`ocum_sudoers` und `ocie_sudoers`) im `/etc/sudoers.d/` Verzeichnis. Wenn Sie diesen Inhalt aufgrund von Sicherheitsrichtlinien oder aufgrund eines Sicherheitsüberwachungstools aus Ihrer Umgebung entfernen, müssen Sie ihn wieder hinzufügen. Sie müssen die sudoers-Konfiguration beibehalten, da für einige Unified Manager-Vorgänge diese sudo-Berechtigungen erforderlich sind.



== Installationsvoraussetzungen

Die Best Practices für die Installation von Red hat Enterprise Linux und den zugehörigen Repositorys auf Ihrem System sind unten aufgeführt. Systeme, die unterschiedlich installiert oder konfiguriert sind oder extern bereitgestellt werden (in der Cloud), erfordern möglicherweise weitere Schritte und Unified Manager kann in solchen Implementierungen nicht ordnungsgemäß ausgeführt werden.

* Sie müssen Red hat Enterprise Linux gemäß den Best Practices von Red hat installieren. Wählen Sie die folgenden Standardoptionen aus, die die Auswahl der Basisumgebung „`Server mit GUI`“ erfordern.
* Bei der Installation von Unified Manager unter Red hat Enterprise Linux muss das System Zugriff auf das entsprechende Repository haben, damit das Installationsprogramm auf alle erforderlichen Softwareabhängigkeiten zugreifen und diese installieren kann.
* Für das `yum` Installer um die abhängige Software in den Red hat Enterprise Linux Repositorys zu finden, müssen Sie das System während der Red hat Enterprise Linux Installation oder danach unter Verwendung eines gültigen Red hat Subskriptions registriert haben.
+
Informationen zum Red hat Subscription Manager finden Sie in der Red hat Dokumentation.

* Sie müssen das EPEL-Repository (Extra Packages for Enterprise Linux) aktivieren, um die erforderlichen Dienstprogramme von Drittanbietern erfolgreich auf Ihrem System installieren zu können.
+
Wenn das EPEL-Repository auf Ihrem System nicht konfiguriert ist, müssen Sie das Repository manuell herunterladen und konfigurieren.

+
Siehe link:task_manually_configure_epel_repository.html["Manuelles Konfigurieren des EPEL-Repositorys"].

* Wenn die korrekte Version von MySQL nicht installiert ist, müssen Sie das MySQL-Repository aktivieren, damit die MySQL-Software auf Ihrem System erfolgreich installiert werden kann.
+
Wenn das MySQL-Repository nicht auf Ihrem System konfiguriert ist, müssen Sie das Repository manuell herunterladen und konfigurieren.

+
Siehe link:task_manually_configure_mysql_repository.html["Manuelles Konfigurieren des MySQL-Repository"].

* Sie müssen nur eine Java-Version auf Ihrem Unified Manager-Host installieren. Andernfalls kann das System möglicherweise nicht bestimmen, welche Version verwendet werden soll. Siehe https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Nach der Java-Aktualisierung auf dem Active IQ Unified Manager-Host werden die Dienste nicht gestartet"].


Wenn Ihr System keinen Internetzugang hat und die Repositories nicht von einem mit dem Internet verbundenen System mit dem nicht verbundenen System gespiegelt werden, sollten Sie die Installationsanweisungen befolgen, um die externen Softwareabhängigkeiten Ihres Systems zu bestimmen. Anschließend können Sie die erforderliche Software auf das mit dem Internet verbundene System herunterladen und die Dateien auf das System kopieren `.rpm`, auf dem Sie Unified Manager installieren möchten. Um die Artefakte und Pakete herunterzuladen, müssen Sie den Befehl verwenden `yum install`. Sie müssen sicherstellen, dass auf den beiden Systemen dieselbe Betriebssystemversion ausgeführt wird und dass die Abonnementlizenz für das entsprechende Red hat Enterprise Linux gilt.

[NOTE]
====
Sie dürfen die erforderliche Drittanbietersoftware nicht aus anderen als den hier aufgeführten Repositorys installieren. Die in den Red hat Repositorys installierte Software wurde speziell für Red hat Enterprise Linux entwickelt und entspricht den Best Practices von Red hat (Verzeichnislayouts, Berechtigungen usw.). Software von anderen Standorten folgt möglicherweise nicht diesen Richtlinien. Dies kann dazu führen, dass die Unified Manager-Installation fehlschlägt oder Probleme mit zukünftigen Upgrades verursachen kann.

====


== Port 443 erforderlich

Allgemeine Images von Red hat Enterprise Linux blockieren möglicherweise den externen Zugriff auf Port 443. Aufgrund dieser Einschränkung können Sie nach der Installation von Unified Manager möglicherweise keine Verbindung zur Administrator-Web-UI herstellen. Mit dem folgenden Befehl können alle externen Benutzer und Anwendungen auf einem allgemeinen Red hat Enterprise Linux auf Port 443 zugreifen.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

Sie müssen Red hat Enterprise Linux mit der Basisumgebung „`Server with GUI`“ installieren. Er stellt die Befehle bereit, die von der Installationsanleitung für Unified Manager verwendet werden. Bei anderen Basisumgebungen müssen Sie möglicherweise zusätzliche Befehle installieren, um die Installation zu validieren oder abzuschließen. Wenn das `firewall-cmd` auf Ihrem System nicht verfügbar ist, müssen Sie es mit dem folgenden Befehl installieren:

`# sudo yum install firewalld`

Wenden Sie sich an Ihre IT-Abteilung, bevor Sie die Befehle ausführen, um zu prüfen, ob Ihre Sicherheitsrichtlinien ein anderes Verfahren erfordern.

[NOTE]
====
THP (Transparent Huge Pages) sollte auf Red hat Systemen deaktiviert werden. Wenn diese Option aktiviert ist, kann dies dazu führen, dass Unified Manager heruntergefahren wird, wenn bestimmte Prozesse zu viel Arbeitsspeicher in Anspruch nehmen und beendet werden.

====