---
permalink: install-linux/task_restart_unified_manager.html 
sidebar: sidebar 
keywords: restart, unified manager 
summary: Möglicherweise müssen Sie Unified Manager neu starten, nachdem Sie die Konfigurationsänderungen vorgenommen haben. 
---
= Neustart Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Unified Manager neu starten, nachdem Sie die Konfigurationsänderungen vorgenommen haben.

*Was Sie brauchen*

Sie müssen Root-Benutzerzugriff auf Red hat Enterprise Linux oder CentOS Server haben, auf dem Unified Manager installiert ist.

.Schritte
. Melden Sie sich als Root-Benutzer an dem Server an, auf dem Sie den Unified Manager-Service neu starten möchten.
. Stoppen Sie den Unified Manager-Dienst und den zugehörigen MySQL-Dienst in dieser Reihenfolge:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
`systemctl stop mysqld`

. Starten Sie die MySQL und Unified Manager Services in dieser Reihenfolge:
+
`systemctl start mysqld`

+
`systemctl start ocie`

+
`systemctl start ocieau`



[NOTE]
====
`mysqld` Ist ein Daemon-Programm erforderlich, um den MySQL-Server zu starten und zu stoppen.

====