---
permalink: include/upgrade-path.html 
sidebar: sidebar 
keywords: supported upgrade path, upgrade path, n-2, which versions can be upgraded 
summary: Unterstützter Upgrade-Pfad 
---
= Unterstützter Upgrade-Pfad für Unified Manager-Versionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager unterstützt für jede Version einen bestimmten Upgrade-Pfad.

Nicht alle Versionen von Unified Manager können ein Upgrade ohne Upgrade auf neuere Versionen durchführen. Die Unified Manager Upgrades sind auf ein N-2-Modell beschränkt, d. h. ein Upgrade kann nur innerhalb der nächsten zwei Versionen auf allen Plattformen durchgeführt werden. Beispielsweise können Sie nur ein Upgrade von Unified Manager 9.11 und 9.12 auf Unified Manager 9.13 durchführen.

Wenn Sie eine Version verwenden, die vor den unterstützten Versionen liegt, muss Ihre Unified Manager Instanz zuerst auf eine der unterstützten Versionen aktualisiert und dann auf die aktuelle Version aktualisiert werden.

Wenn Sie beispielsweise OnCommand Unified Manager 9.6 installiert haben und auf die neueste Version Active IQ Unified Manager 9.13 aktualisieren möchten, folgen Sie einer Reihe von Upgrades.

.Beispiel für ein Upgrade-Pfad:
. Führen Sie ein Upgrade von OnCommand Unified Manager 9.6 -> Active IQ Unified Manager 9.8 durch
. Upgrade 9.8 -> 9.10
. Upgrade 9.10 -> 9.12
. Upgrade 9.12 -> 9.13


Weitere Informationen zur Upgrade-Pfad-Matrix finden Sie hier https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_the_upgrade_path_for_Active_IQ_Unified_Manager_versions["Knowledge Base-Artikel (KB"].
