---
permalink: data-protection/task_restore_data_use_health_volume_details_page.html 
sidebar: sidebar 
keywords: restore, data, volume, health details page 
summary: Mit der Wiederherstellungsfunktion auf der Seite „Volume/Health Details“ können Sie überschreibte oder gelöschte Dateien, Verzeichnisse oder ein gesamtes Volume anhand einer Snapshot Kopie wiederherstellen. 
---
= Wiederherstellen von Daten mithilfe der Seiten Volume- und Volume-/Health-Details
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können überschreibte oder gelöschte Dateien, Verzeichnisse oder ein gesamtes Volume anhand einer Snapshot Kopie wiederherstellen. Hierzu verwenden Sie die Wiederherstellungsfunktion auf den Seiten „Volume and Volume/Health Details“.

*Was Sie brauchen*

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.


NOTE: Beachten Sie folgende Punkte:

* NTFS-Dateiströme können nicht wiederhergestellt werden.
* Die Wiederherstellungsoption ist nicht verfügbar, wenn:
+
** Die Volume-ID ist unbekannt, z. B. wenn Sie eine Intercluster-Beziehung haben und der Ziel-Cluster noch nicht erkannt wurde.
** Das Volume ist für die synchrone SnapMirror Replizierung konfiguriert.




.Schritte
. Klicken Sie im linken Navigationsbereich auf *Speicherung > Volumes*.
. Wählen Sie die Lautstärke aus und klicken Sie auf die Schaltfläche *Wiederherstellen*. Klicken Sie alternativ auf das Volume, um zu *Volume / Health Details > Aktionen > Wiederherstellen* zu wechseln. Das Dialogfeld Wiederherstellen wird angezeigt. Informationen zu dieser Seite finden Sie unter link:../data-protection/reference_restore_dialog_box.html["Dialogfeld „Wiederherstellen“"].
. Wählen Sie das Volume und die Snapshot Kopie aus, von dem Sie Daten wiederherstellen möchten, falls sie sich von dem Standard unterscheiden.
. Wählen Sie die Elemente aus, die wiederhergestellt werden sollen, z. B. die Quell-LUN.
+
Sie können das gesamte Volume wiederherstellen oder Ordner und Dateien angeben, die wiederhergestellt werden sollen.

. Wählen Sie den Speicherort aus, an dem die ausgewählten Elemente wiederhergestellt werden sollen: Entweder *Originalstandort* oder *alternativer bestehender Standort*.
. Wenn Sie einen alternativen vorhandenen Standort auswählen, führen Sie einen der folgenden Schritte aus:
+
** Geben Sie im Textfeld Pfad wiederherstellen den Pfad des Speicherorts ein, zu dem die Daten wiederhergestellt werden sollen, und klicken Sie dann auf *Verzeichnis auswählen*.
** Klicken Sie auf *Durchsuchen*, um das Dialogfeld Verzeichnisse durchsuchen zu starten und führen Sie die folgenden Schritte aus:
+
... Wählen Sie das Ziel-Cluster, die Storage VM (SVM) und das Volume aus, das Sie wiederherstellen möchten.
... Wählen Sie in der Tabelle Name einen Verzeichnisnamen aus, der wiederhergestellt werden soll.
... Klicken Sie Auf *Verzeichnis Auswählen*.




. Klicken Sie Auf *Wiederherstellen*.
+
Der Wiederherstellungsprozess beginnt. Zum Abschluss des Wiederherstellungsprozesses wird im Backend ein Job erstellt.

. Wenn Sie den Job-Fortschritt anzeigen möchten, navigieren Sie im linken Navigationsbereich zu *Schutz > Jobs*, um den Status des Wiederherstellungsjobs aus der Liste der Jobs anzuzeigen.
+
[NOTE]
====
Wenn eine Wiederherstellung zwischen Cloud Volumes ONTAP HA Clustern mit einem NDMP-Fehler fehlschlägt, müssen Sie möglicherweise eine explizite AWS Route im Ziel-Cluster hinzufügen, damit das Ziel mit der Cluster-Management-LIF des Quellsystems kommunizieren kann. Sie führen diese Konfiguration mithilfe von BlueXP aus.

====

