---
permalink: data-protection/view-lun-relationships.html 
sidebar: sidebar 
keywords: LUN, SnapMirror active sync, Consistency Group, CG 
summary: Einheitliche Ansicht der durch SnapMirror aktiven Sync geschützten LUNs. 
---
= Überwachen von LUNs in einer Konsistenzgruppenbeziehung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihre ONTAP Umgebung die aktive SnapMirror Synchronisierung mit unterstützt
Schützen Sie Applikationen mit LUNs, und Sie können diese LUNs auf der Active IQ Unified Manager anzeigen und überwachen.

SnapMirror Active Sync sorgt für null Recovery Time Objective (RTO) während des Failovers in SAN-Umgebungen. In einer typischen Bereitstellung, die SnapMirror Active Sync unterstützt, sind die LUNs auf Volumes durch Beziehungen zu Konsistenzgruppen geschützt.

Diese primären und sekundären LUNs sind zusammengesetzte LUNs oder ein LUN-Replikatpaar mit derselben UUID und Seriennummer. Die I/O-Vorgänge (sowohl Lese- als auch Schreibvorgänge) werden über die Quell- und Zielstandorte auf diesen zusammengesetzten LUNs multipliziert, wodurch Transparenz gewährleistet wird.

Zur Anzeige zusammengesetzter LUNs sollten sowohl die primären als auch die sekundären Cluster mit den LUNs, die Teil der Consistency Group-Beziehung sind, hinzugefügt und in Unified Manager entdeckt werden. Es werden nur iSCSI- und FCP-LUNs unterstützt.

Informationen zur aktiven SnapMirror Synchronisierung finden Sie unter link:https://docs.netapp.com/us-en/ontap/smbc/index.html["ONTAP 9 Dokumentation für SnapMirror Active Sync (ehemals SM-BC)"].

Um sich zusammengesetzte LUNs in Ihrer Umgebung anzusehen, folgen Sie den folgenden Schritten:

.Schritte
. Klicken Sie im linken Navigationsbereich auf *Storage* > *LUNs*.
. Wählen Sie im Menü Ansicht die Option *Beziehung* > *Alle LUNs*.
+
Die Beziehung: Alle LUNs-Ansicht wird angezeigt.



Sie können die LUN-Details anzeigen, z. B. den LUN-Namen, das Volume, eine Storage-VM mit LUN, Cluster, Konsistenzgruppe und der Partner-LUN. Sie können auf jede dieser Komponenten klicken, um eine detaillierte Ansicht aufzurufen. Wenn Sie auf die Konsistenzgruppe klicken, gelangen Sie zur Seite Beziehungen.

Durch Klicken auf die Partner-LUN können Sie die Konfigurationsdetails auf der Registerkarte SAN auf der Seite Storage VM Details der Storage VM anzeigen, auf der die Partner-LUN gehostet wird. Informationen wie die Initiatoren, Initiatorgruppen und andere Aspekte der Partner-LUN werden angezeigt.

Sie können die standardmäßigen Funktionen auf Grid-Ebene zum Sortieren, Filtern, Erstellen und Hochladen von Berichten für die geschützten LUNs in Ihrer Umgebung ausführen.
